### PR TITLE
Fixed RouteStep.exitIndex parsing

### LINKED ISSUE #508: RouteStep exitIndex not filled with roundabout
Hello all,

According to documentation, exitIndex should indicate the number of exits from the approach to the recommended outlet when the maneuver is a roundabout.
From my experience, this is not working and exitIndex is always nil.

### PR DESCRIPTION
**Pull request by S2Ler**
It was expected that exitIndex was at the top level of RouteStep json
dictionary. But it is actually at "maneuver" sub dictionary.

Fixes #508 and mapbox/mapbox-navigation-ios#2742

### CODE REVIEW

File: Tests/MapboxDirectionsTests/RouteStepTests.swift [hunk 1]
```diff
@@ -336,14 +336,19 @@ class RouteStepTests: XCTestCase {
             var newRoute: Route?
             XCTAssertNoThrow(newRoute = try decoder.decode(Route.self, from: jsonData))
             XCTAssertNotNil(newRoute)
+            guard let leg = newRoute?.legs.first else {
+                XCTFail("No Logs Found"); return
```
Comment (1ec5) [inline Tests/MapboxDirectionsTests/RouteStepTests.swift:340]:
```suggestion
                XCTFail("No legs found"); return
```

**Review by 1ec5 — APPROVED** [review]
Suggested changelog entry:

* Fixed an issue where `RouteStep.exitIndex` was always unset. ([#567](https://github.com/mapbox/mapbox-directions-swift/pull/567))

File: Tests/MapboxDirectionsTests/RouteStepTests.swift (hunk 1 above)
Comment (S2Ler) [reply Tests/MapboxDirectionsTests/RouteStepTests.swift:340]: done
