### PR TITLE
Fix backwards incompatible associated value in shield implementation

### LINKED ISSUE #646: Backwards-incompatible associated value added to VisualInstruction.Component case
#644 renamed `VisualInstruction.Component.image(image:alternativeText:)` to `VisualInstruction.Component.image(image:alternativeText:shield:)`. Even though the `shield` parameter has a default argument, `switch` statements that capture the arguments of `image` will be broken because the number of arguments has changed. The only way to maintain backwards compatibility is to revert `image` to how it was and introduce a new `shield` case that has the `shield` parameter.

/ref https://github.com/mapbox/mapbox-directions-swift/pull/644#discussion_r795025081
/cc @jill-cardamon @bamx23

### PR DESCRIPTION
**Pull request by jill-cardamon**
This PR fixes #646 by making `shield` an optional property of `VisualInstruction.Component.ImageRepresentation`.

cc/ @1ec5 @bamx23

### CODE REVIEW

File: Sources/MapboxDirections/VisualInstructionComponent.swift [hunk 1]
```diff
@@ -178,11 +183,11 @@ public extension VisualInstruction.Component {
         /**
          Initializes a mapbox shield with the given name, text color, and display ref.
          */
-        public init(baseURL: URL, name: String, textColor: String, text: String) {
+        public init(baseURL: URL, name: String, textColor: String, code: String) {
```
Comment (bamx23) [inline Sources/MapboxDirections/VisualInstructionComponent.swift:186]: Why do we need this change? As it's a backward-incompatible one.

Comment (jill-cardamon) [reply Sources/MapboxDirections/VisualInstructionComponent.swift:186]: It was to not interfere with `text` in the coding keys. I can actually change it back.

**Review by bamx23 — APPROVED** [review]
